modLoader = "javafml"
loaderVersion = "[52,)"
license = "MIT"

[[mods]]
modId = "soundcreator"
version = "${file.jarVersion}"
displayName = "SoundCreator"
description = "Reproduce archivos de audio del servidor via PlasmoVoice."
authors = "ELB_GG"

[[dependencies.soundcreator]]
modId = "forge"
mandatory = true
versionRange = "[52,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.soundcreator]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "SERVER"
